name: baseball
channels:
  - anaconda
  - conda-forge
  - defaults
dependencies:
  - flask=1.1.2
  - numpy=1.18.5
  - pandas=1.0.5
  - pip=20.1.1
  - python=3.8.3
  - scikit-learn=0.23.1
  - seaborn=0.10.1
  - tqdm=4.47.0
  - pip:
    - mlb-statsapi==0.1.7

