FROM continuumio/miniconda3:latest

ENV PYTHONDONTWRITEBYTECODE=true

RUN conda install --yes --freeze-installed \
	nomkl \
	pandas \ 
	scikit-learn \ 
	sqlalchemy \
	psycopg2

RUN conda install -c conda-forge xgboost
RUN conda clean -afy

RUN pip install google-cloud-storage

COPY utils_config.py ./
COPY cloud_storage.py ./
COPY postgres_upload.py ./
COPY train_model.py ./
COPY data/ data/

ENTRYPOINT ["python", "train_model.py"]