FROM continuumio/miniconda3:latest

WORKDIR /app

ENV PYTHONDONTWRITEBYTECODE=true

RUN conda install --yes --freeze-installed \
	nomkl \
	pandas \
	&& conda clean -afy

RUN pip install mlb-statsapi
RUN pip install google-cloud-storage

COPY utils_config.py ./
COPY api_utils.py ./
COPY cloud_storage.py ./
COPY retrieve_data.py ./
COPY data/ data/
COPY /credentials/ credentials/

COPY .env ./
RUN pip install python-dotenv

ENTRYPOINT ["python", "retrieve_data.py"]